name: matchwise
description: "RA matching website"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  resize: ^1.0.0
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  gap: ^3.0.1
  auto_size_text: ^3.0.0
  flutter_riverpod: ^2.5.1
  oktoast: ^3.4.0
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  package_info_plus: ^8.1.0
  dio: ^5.7.0
  fuzzy: ^0.5.1
  cloud_firestore: ^5.5.0
  url_launcher: ^6.3.1
  cloud_functions: ^5.2.0
  csv: ^6.0.0
  file_saver: ^0.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/icons/

